logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
server:
  port: 9000
spring:
  application:
    name: api-zuul
  sleuth:
    enabled: true
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url:
        - http://localhost:7000
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    pet-visit:
      path: /visit/**
      service-id: pet-visit
    pet-appointment:
      path: /appointment/**
      service-id: pet-appointment
    doctor-service:
      path: /doctor/**
      service-id: doctor-service
    customer-service:
      path: /customer/**
      service-id: customer-service
    pet-microservice:
      path: /pet/**
      service-id: pet-microservice
